# Generated by Django 6.0.4 on 2026-09-25 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Ensino Médio, Ensino Fundamental', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveis_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveis_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nível de Ensino',
                'verbose_name_plural': 'Níveis de Ensino',
                'ordering': ['tipo_grade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nome', models.CharField(help_text='Ex: 1º Ano, 2º Semestre', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_criados', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='educacional.nivelensino')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['numero'],
                'unique_together': {('nivel', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TipoGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Anual, Semestral, Modular', max_length=100)),
                ('quantidade_series', models.PositiveIntegerField(help_text='Quantidade total de etapas (ex: 3, 8, 9)')),
                ('sufixo', models.CharField(help_text='Ex: Ano, Semestre, Módulo', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_grade_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_grade_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Grade',
                'verbose_name_plural': 'Tipos de Grade',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='nivelensino',
            name='tipo_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveis', to='educacional.tipograde'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Manhã, Tarde', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-data_criacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='A, B, C...', max_length=10)),
                ('ano_letivo', models.PositiveIntegerField()),
                ('periodo_letivo', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidade', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_criados', to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='educacional.serie')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educacional.turno')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['serie', 'ano_letivo', 'periodo_letivo'],
            },
        ),
        migrations.AddIndex(
            model_name='tipograde',
            index=models.Index(fields=['-quantidade_series'], name='educacional_quantid_9862ac_idx'),
        ),
        migrations.AddIndex(
            model_name='nivelensino',
            index=models.Index(fields=['tipo_grade', 'nome'], name='educacional_tipo_gr_b08735_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['-data_criacao'], name='educacional_data_cr_fcb19d_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['serie'], name='educacional_serie_i_d18a36_idx'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(condition=models.Q(('periodo_letivo__isnull', False)), fields=('nome', 'serie', 'turno', 'ano_letivo', 'periodo_letivo'), name='unique_turma_com_periodo'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(condition=models.Q(('periodo_letivo__isnull', True)), fields=('nome', 'serie', 'turno', 'ano_letivo'), name='unique_turma_sem_periodo'),
        ),
    ]
