# Generated by Django 6.0.4 on 2026-09-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('educacional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_criados', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['-data_criacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido'), ('formado', 'Formado'), ('trancado', 'Trancado')], default='ativo', max_length=15)),
                ('ra', models.CharField(max_length=50, unique=True)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='aluno.aluno')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('matriculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_criadas', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educacional.nivelensino')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educacional.serie')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='educacional.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'ordering': ['-data_matricula', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['-data_criacao'], name='aluno_aluno_data_cr_af0150_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['-data_matricula'], name='aluno_matri_data_ma_f09606_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('ra', 'turma')},
        ),
    ]
